[build]
  command = "echo \"export const environment = { production: true, apiBaseUrl: '${NG_ENV_API_BASE_URL}' };\" > src/app/core/environments/environment.ts && ng build --configuration production"
  functions = "netlify/functions"
  publish = "dist/virellarent-frontend/browser"

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
